import getData from "@/lib/fetch/getData";

export default async function Head({ params }: { params: { slug: string[] } }) {
  const data = await getData(params.slug ? params.slug.join('/') : '');

  return (
    <>
      <title>Create Next App</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </>
  )
}
